export const dummyData = [
  {
    id: 1,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 2,
    WorkPlan: "D13",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 3,
    WorkPlan: "D14",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 4,
    WorkPlan: "D16",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 5,
    WorkPlan: "D18",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 6,
    WorkPlan: "D20",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 7,
    WorkPlan: "D22",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 8,
    WorkPlan: "D23",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 9,
    WorkPlan: "D25",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 10,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 11,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 12,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 13,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 14,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 15,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
  {
    id: 16,
    WorkPlan: "D12",
    Active: "Y",
    Sun: "D12",
    Mon: "D15",
    Tue: "D16",
    Wed: "D18",
    Thu: "D20",
    Fri: "D21",
    Sat: "D22",
  },
];

export const modalDayMock = [
  {
    label: "Sun",
    shift: "Shift",
    style: "",
    name: "sun",
    duration: "D1",
  },
  {
    label: "Mon",
    shift: "Shift",
    style: "",
    name: "Mon",
    duration: "D2",
  },
  {
    label: "Tue",
    shift: "Shift",
    style: "",
    name: "Tue",
    duration: "D3",
  },
  {
    label: "Wed",
    shift: "Shift",
    style: "",
    name: "wed",
    duration: "D4",
  },
  {
    label: "Thu",
    shift: "Shift",
    style: "",
    name: "Thu",
    duration: "D5",
  },
  {
    label: "Fri",
    shift: "Shift",
    style: "",
    name: "Fri",
    duration: "D6",
  },
  {
    label: "Sat",
    shift: "Shift",
    style: "",
    name: "Sat",
    duration: "D7",
  },
];
// const [days, setDays] = (useState = {
//   d1: "",
//   d2: "",
//   d3: "",
//   d4: "",
// });
